<a href="https://colab.research.google.com/github/kaweetakumari314-creator/Pandas/blob/main/Pandas_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Kaweeta Kumari**
# **AI-875087**

**1. Import Pandas**

In [ ]:
import pandas as pd  #pd is shprt name for pandas

**Pandas Functions**

In [ ]:
#pd.DataFrame()
#pd.read_csv()
#pd.concat()
#pd.merge()

**2. Creating a Dataframe**

In [ ]:
Data = {
    "Name": ["kaweeta", "Hina", "Sonia", "Aleena", "Nudrat"],
    "Roll-No": [213, 432, 567, 908, 678],
    "Courses": ["Data Science", "AI", "CyberSecurity", "Data Science", "AI"],
    "Marks": [70, 91, 88, 67, 79]
}
ds = pd.DataFrame(Data)
ds

      Name  Roll-No        Courses  Marks
0  kaweeta      213   Data Science     70
1     Hina      432             AI     91
2    Sonia      567  CyberSecurity     88
3   Aleena      908   Data Science     67
4   Nudrat      678             AI     79

**3. Reading a Dataset**

- Download a dataset from Kaggle or any open source
- Upload that file (csv\excel\json) etc in colab notebook
- Read that file using pandas read function.

In [ ]:
df = pd.read_csv("/content/Social_media_impact_on_life.csv")
df

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

**4. Viewing Data**

- We cannot see the whole dataset but there are ways to see parts of it to analyze what type of data it is. It includes:

-head(): It shows first five rows by defauls but we can give number in paranthesis we we want to see more than five rows.

-tail(): It shows last five rows by default.

-sample(): Shows random rows.

In [ ]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial

In [ ]:
df.tail()

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
df.sample()

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
3018,STU_2027018,21,Female,Undergraduate,Instagram,6.8,2.1,Smartphone,6.4,1,True,Rarely,12.0,88,3.28,Beneficial

**5. Shape and Basic Properties**

In [ ]:
#shape(): It tells the number of rows and columns in the dataset
df.shape

(4500, 16)

In [ ]:
#columns: We can see the colmun names through this method.
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='object')

In [ ]:
#dtype : It tells the datatypes of all the columns in the dataset
df.dtypes

Student_ID                      object
Age                              int64
Gender                          object
Academic_Level                  object
Primary_Platform                object
Daily_Usage_Hours              float64
Weekend_Extra_Hours            float64
Device_Type                     object
Sleep_Duration_Hours           float64
Sleep_Quality_Score              int64
Late_Night_Usage                  bool
Social_Comparison_Frequency     object
Perceived_Stress_Score         float64
Mental_Health_Index              int64
Academic_Performance_GPA       float64
Overall_Impact                  object
dtype: object

**6. Dataframes Information**
df.info()-  It tells us:

1. no of rows
2. no of columns
3. column names
4. Data types
5. Missing values
6. memory usage

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int64(3), object(7)
memory usage: 531.9+ KB

**7. Statistical Summary**

-describe() method gives statistical summary of numerical columns

In [ ]:
df.describe()

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4454.000000,4500.000000,4415.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.072859,12.876044,0.392662
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.460000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

**8. Selecting Columns**

- we can select column/columns to apply methods on them.

In [ ]:
#Selecting one column
df["Student_ID"]

0       STU_2024000
1       STU_2024001
2       STU_2024002
3       STU_2024003
4       STU_2024004
           ...
4495    STU_2028495
4496    STU_2028496
4497    STU_2028497
4498    STU_2028498
4499    STU_2028499
Name: Student_ID, Length: 4500, dtype: object

In [ ]:
#Selecting multiple columns
df[["Student_ID", "Age"]]

       Student_ID  Age
0     STU_2024000   19
1     STU_2024001   19
2     STU_2024002   17
3     STU_2024003   16
4     STU_2024004   17
...           ...  ...
4495  STU_2028495   16
4496  STU_2028496   19
4497  STU_2028497   19
4498  STU_2028498   16
4499  STU_2028499   24

[4500 rows x 2 columns]

**9. Selecting Rows- loc and iloc**

- loc selcets data using index labels.
- iloc selects data using position.

In [ ]:
df.loc[0] # selecting first row

Student_ID                       STU_2024000
Age                                       19
Gender                                Female
Academic_Level                 Undergraduate
Primary_Platform                    Snapchat
Daily_Usage_Hours                        7.5
Weekend_Extra_Hours                      1.5
Device_Type                       Smartphone
Sleep_Duration_Hours                     5.9
Sleep_Quality_Score                        2
Late_Night_Usage                        True
Social_Comparison_Frequency           Always
Perceived_Stress_Score                  20.0
Mental_Health_Index                       73
Academic_Performance_GPA                2.73
Overall_Impact                       Neutral
Name: 0, dtype: object

In [ ]:
#df.loc[0, "Age"] #selceting particular value
df.loc[1, "Academic_Level"]

'Undergraduate'

In [ ]:
df.iloc[0]

Student_ID                       STU_2024000
Age                                       19
Gender                                Female
Academic_Level                 Undergraduate
Primary_Platform                    Snapchat
Daily_Usage_Hours                        7.5
Weekend_Extra_Hours                      1.5
Device_Type                       Smartphone
Sleep_Duration_Hours                     5.9
Sleep_Quality_Score                        2
Late_Night_Usage                        True
Social_Comparison_Frequency           Always
Perceived_Stress_Score                  20.0
Mental_Health_Index                       73
Academic_Performance_GPA                2.73
Overall_Impact                       Neutral
Name: 0, dtype: object

In [ ]:
df.iloc[0, 4] #df.iloc[row position, column position]

'Snapchat'

**10. Filtering Data**

- Selecting data that matches some condition.

In [ ]:
df['Age'].value_counts()

Age
18    1028
19     902
17     716
20     630
21     356
16     340
22     178
15     164
23      85
24      50
26      29
25      22
Name: count, dtype: int64

In [ ]:
df['Age'].nunique()

12

In [ ]:
# Filtering those students who are under 18.
minor = df[df['Age']<18]
minor

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
5,STU_2024005,16,Male,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
10,STU_2024010,15,Female,High School,TikTok,4.4,1.9,Smartphone,5.8,2,False,Frequently,11.0,83,3.22,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4483,STU_2028483,17,Female,High School,TikTok,5.3,2.2,Smartphone,6.5,3,True,Frequently,13.0,82,3.02,Beneficial
4487,STU_2028487,17,Prefer not to say,High School,Instagram,8.8,2.5,Smartphone,6.2,1,True,Frequently,21.0,68,3.50,Beneficial
4494,STU_2028494,16,Male,High School,YouTube,5.2,1.6,Smartphone,5.7,3,True,Sometimes,24.0,77,3.31,Neutral
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial

In [ ]:
others = df[~df['Gender'].isin(['Male', 'Female'])]
others

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
13,STU_2024013,23,Non-Binary,Undergraduate,Instagram,1.9,1.2,Smartphone,8.9,5,False,Sometimes,3.0,95,3.86,Beneficial
51,STU_2024051,19,Prefer not to say,High School,X (Twitter),2.9,1.6,Smartphone,6.7,2,True,Always,7.0,95,3.57,Beneficial
79,STU_2024079,20,Prefer not to say,Undergraduate,Snapchat,6.2,2.2,Smartphone,6.8,2,True,Rarely,13.0,82,3.41,Beneficial
89,STU_2024089,18,Non-Binary,Undergraduate,Reddit,14.0,1.8,Smartphone,4.7,1,True,Frequently,35.0,50,2.00,Negative
102,STU_2024102,21,Non-Binary,Undergraduate,X (Twitter),3.1,1.6,Smartphone,7.7,3,False,Frequently,4.0,98,3.67,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4435,STU_2028435,19,Non-Binary,Undergraduate,Instagram,2.7,1.5,Smartphone,8.4,3,False,Frequently,7.0,98,3.59,Beneficial
4446,STU_2028446,19,Prefer not to say,Undergraduate,Instagram,3.1,2.3,Smartphone,9.0,5,True,Frequently,13.0,78,4.00,Beneficial
4462,STU_2028462,19,Prefer not to say,Undergraduate,Instagram,5.4,1.8,Smartphone,6.2,2,True,Frequently,15.0,80,3.42,Beneficial
4487,STU_2028487,17,Prefer not to say,High School,Instagram,8.8,2.5,Smartphone,6.2,1,True,Frequently,21.0,68,3.50,Beneficial
4489,STU_2028489,21,Prefer not to say,High School,TikTok,2.8,3.2,Smartphone,7.2,4,True,Rarely,6.0,98,3.86,Beneficial

**11. Adding a new column in dataset**

In [ ]:
ds

      Name  Roll-No        Courses  Marks
0  kaweeta      213   Data Science     70
1     Hina      432             AI     91
2    Sonia      567  CyberSecurity     88
3   Aleena      908   Data Science     67
4   Nudrat      678             AI     79

In [ ]:
#Lets add a column named as Grade in our datset
ds["Grade"]= ["C", "A", "B", "D", "C"]
ds

      Name  Roll-No        Courses  Marks Grade
0  kaweeta      213   Data Science     70     C
1     Hina      432             AI     91     A
2    Sonia      567  CyberSecurity     88     B
3   Aleena      908   Data Science     67     D
4   Nudrat      678             AI     79     C

**12. Updating Values**

- We can change existing values in a dataframe

In [ ]:
# lets update Kaweeta's marks from 70 to 87
ds.loc[0, "Marks"] = 87
ds

      Name  Roll-No        Courses  Marks Grade
0  kaweeta      213   Data Science     87     C
1     Hina      432             AI     91     A
2    Sonia      567  CyberSecurity     88     B
3   Aleena      908   Data Science     67     D
4   Nudrat      678             AI     79     C

In [ ]:
# We can also update entire marks column
ds["Marks"] = ds["Marks"] + 5
ds

      Name  Roll-No        Courses  Marks Grade
0  kaweeta      213   Data Science     92     C
1     Hina      432             AI     96     A
2    Sonia      567  CyberSecurity     93     B
3   Aleena      908   Data Science     72     D
4   Nudrat      678             AI     84     C

**13. Deleting Rows and Columns**

- Pandas uses drop method to delete/remove data
- axis = 0 -> Row (set by default, no need to mention)
- axis = 1 -> Column (need to mention this)

In [ ]:
# For deleting row, just give row index

ds.drop(0)

     Name  Roll-No        Courses  Marks Grade
1    Hina      432             AI     96     A
2   Sonia      567  CyberSecurity     93     B
3  Aleena      908   Data Science     72     D
4  Nudrat      678             AI     84     C

In [ ]:
#for deleting column, we have to give column name and write axis = 1
# axis = 1, will tell it that we want to delete a column.

ds.drop("Grade", axis = 1)

      Name  Roll-No        Courses  Marks
0  kaweeta      213   Data Science     92
1     Hina      432             AI     96
2    Sonia      567  CyberSecurity     93
3   Aleena      908   Data Science     72
4   Nudrat      678             AI     84

**14. Handling Missing Values**

- Real datasets often contain missing data/values.
- Check missing values using isnull() and isnull().sum() methods to count missing values.

- Remove missing values using df.dropna()
- Fill missing values using df.fillna(): fillna(0) will fill zero in empty cells and fillna().mean() will fill cells with the mean of other rows.

In [ ]:
df.isnull()

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Primary_Platform                0
Daily_Usage_Hours               0
Weekend_Extra_Hours             0
Device_Type                     0
Sleep_Duration_Hours            0
Sleep_Quality_Score             0
Late_Night_Usage                0
Social_Comparison_Frequency     0
Perceived_Stress_Score         46
Mental_Health_Index             0
Academic_Performance_GPA       85
Overall_Impact                  0
dtype: int64

In [ ]:
# df.dropna() -This will remove all the rows containing missing values

In [ ]:
# df.fillna(0) - This will fill 0 where there is empty cell in dataframe/dataset.

In [ ]:
# Lets fill the missing values in column 'Perceived_Stress_Score' with mean()

df['Perceived_Stress_Score'] = df['Perceived_Stress_Score'].fillna(df['Perceived_Stress_Score'].mean())
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Primary_Platform                0
Daily_Usage_Hours               0
Weekend_Extra_Hours             0
Device_Type                     0
Sleep_Duration_Hours            0
Sleep_Quality_Score             0
Late_Night_Usage                0
Social_Comparison_Frequency     0
Perceived_Stress_Score          0
Mental_Health_Index             0
Academic_Performance_GPA       85
Overall_Impact                  0
dtype: int64

In [ ]:
# Lets fill the missing values in column 'Academic_Performance_GPA' with zero
df['Academic_Performance_GPA'] = df['Academic_Performance_GPA'].fillna(0)
df.isnull().sum()

Student_ID                     0
Age                            0
Gender                         0
Academic_Level                 0
Primary_Platform               0
Daily_Usage_Hours              0
Weekend_Extra_Hours            0
Device_Type                    0
Sleep_Duration_Hours           0
Sleep_Quality_Score            0
Late_Night_Usage               0
Social_Comparison_Frequency    0
Perceived_Stress_Score         0
Mental_Health_Index            0
Academic_Performance_GPA       0
Overall_Impact                 0
dtype: int64

**15. Handling Duplicate Data**

In [ ]:
df

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4495    False
4496    False
4497    False
4498    False
4499    False
Length: 4500, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
ds

      Name  Roll-No        Courses  Marks Grade
0  kaweeta      213   Data Science     92     C
1     Hina      432             AI     96     A
2    Sonia      567  CyberSecurity     93     B
3   Aleena      908   Data Science     72     D
4   Nudrat      678             AI     84     C

In [ ]:
data = {
    "Name": ["kaweeta", "Hina", "Sonia", "Aleena", "Nudrat", "kaweeta"],
    "Roll-No": [213, 432, 567, 908, 678, 213]
}
df4 = pd.DataFrame(data)
df4

      Name  Roll-No
0  kaweeta      213
1     Hina      432
2    Sonia      567
3   Aleena      908
4   Nudrat      678
5  kaweeta      213

In [ ]:
df4.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [ ]:
df4.duplicated().sum()

np.int64(1)

In [ ]:
#Lets drop the duplicate row, removing duplicates is part of data cleaning
df4.drop_duplicates()

      Name  Roll-No
0  kaweeta      213
1     Hina      432
2    Sonia      567
3   Aleena      908
4   Nudrat      678

**16. Sorting Data**

- We use sort_values() method to sort values.
- By default it is in ascending order.
- For sorting in descending order we will give a parameter ascending = False.

In [ ]:
df['Academic_Performance_GPA']

0       2.73
1       3.21
2       3.00
3       3.42
4       3.41
        ...
4495    2.85
4496    3.37
4497    3.16
4498    3.50
4499    3.73
Name: Academic_Performance_GPA, Length: 4500, dtype: float64

In [ ]:
df.sort_values('Academic_Performance_GPA')
df['Academic_Performance_GPA']

0       2.73
1       3.21
2       3.00
3       3.42
4       3.41
        ...
4495    2.85
4496    3.37
4497    3.16
4498    3.50
4499    3.73
Name: Academic_Performance_GPA, Length: 4500, dtype: float64

In [ ]:
df.sort_values('Academic_Performance_GPA', ascending = False)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
24,STU_2024024,18,Female,Undergraduate,YouTube,3.4,1.7,Smartphone,8.2,4,False,Frequently,8.0,90,4.0,Beneficial
787,STU_2024787,21,Female,Undergraduate,Snapchat,3.4,1.8,Smartphone,8.6,5,False,Sometimes,7.0,98,4.0,Beneficial
815,STU_2024815,22,Female,Undergraduate,TikTok,2.1,1.9,Laptop/PC,7.6,3,False,Frequently,13.0,97,4.0,Beneficial
811,STU_2024811,19,Prefer not to say,Undergraduate,YouTube,2.8,2.3,Smartphone,7.7,3,True,Rarely,2.0,98,4.0,Beneficial
810,STU_2024810,20,Male,Undergraduate,YouTube,2.5,2.9,Smartphone,7.9,3,False,Frequently,0.0,98,4.0,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3402,STU_2027402,20,Male,Undergraduate,TikTok,6.2,2.4,Smartphone,7.4,3,True,Frequently,15.0,85,0.0,Beneficial
4452,STU_2028452,24,Female,Undergraduate,YouTube,3.6,1.4,Laptop/PC,7.7,3,True,Frequently,11.0,92,0.0,Beneficial
3752,STU_2027752,15,Female,High School,YouTube,3.4,0.7,Smartphone,6.8,1,False,Frequently,9.0,89,0.0,Beneficial
39,STU_2024039,17,Male,High School,TikTok,3.3,1.7,Laptop/PC,6.0,1,False,Frequently,15.0,87,0.0,Beneficial
44,STU_2024044,21,Female,Undergraduate,Instagram,7.6,1.6,Smartphone,5.9,1,True,Rarely,25.0,70,0.0,Neutral

**17. Aggregation And Groupby**

Aggregation gives us summary values like:
- sum()
- max() #maximum
- min() # minimum
- count()
- mean()

groupby() allows us analyze data according to categories.

In [ ]:
ds

      Name  Roll-No        Courses  Marks Grade
0  kaweeta      213   Data Science     92     C
1     Hina      432             AI     96     A
2    Sonia      567  CyberSecurity     93     B
3   Aleena      908   Data Science     72     D
4   Nudrat      678             AI     84     C

In [ ]:
marks = ds["Marks"]

In [ ]:
marks.min()

72

In [ ]:
marks.max()

96

In [ ]:
marks.mean()

np.float64(87.4)

In [ ]:
marks.count()

np.int64(5)

In [ ]:
marks.sum()

np.int64(437)

In [ ]:
# groupby()

ds.groupby("Courses")["Marks"].mean()

Courses
AI               90.0
CyberSecurity    93.0
Data Science     82.0
Name: Marks, dtype: float64

In [ ]:
df.groupby("Gender")["Age"].mean()

Gender
Female               18.697404
Male                 18.700634
Non-Binary           18.819672
Prefer not to say    18.752688
Name: Age, dtype: float64

**18. Combining Dataframes**

Pandas allows us to combine two dataframes in one so that we can analyze it better if both have related info.

we have two way to do this:
- concat() : It is used to join similar datasets vertically.

- merge() : combines DataFrames using a common column.

In [ ]:
section_A = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks": [70, 85, 60, 95, 45]
}

section_B = {
    "Name": ["Mariyum", "Fatima"],
    "Marks": [80, 74]
}

courses = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Courses": ["AI", "Web", "AI", "Web", "AI"]
}

df1 = pd.DataFrame(section_A)
df2 = pd.DataFrame(section_B)
df3 = pd.DataFrame(courses)

In [ ]:
# combining both Dataframes that we just created using concat() method.

pd.concat([df1, df2], ignore_index = True)

      Name  Marks
0      Ali     70
1     Sara     85
2    Ahmed     60
3   Ayesha     95
4     Zain     45
5  Mariyum     80
6   Fatima     74

In [ ]:
# combining both Dataframes that we just created using merge() method.
pd.merge(df1, df3, on = "Name")

     Name  Marks Courses
0     Ali     70      AI
1    Sara     85     Web
2   Ahmed     60      AI
3  Ayesha     95     Web
4    Zain     45      AI

**Task 01- creating student dataframe:**

In [ ]:
std_data = {
    "Name" : ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks": [70, 85, 60, 95, 45]
}

ds=pd.DataFrame(std_data)
ds

     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
4    Zain     45

In [ ]:
marks = ds["Marks"]

#Average marks:
print("Average of Marks is: ")
print(marks.mean())

#Maximum marks:
print("Maximum value in Marks is: ")
print(marks.max())

#Minimum marks:
print("Minimum value in Marks is: ")
print(marks.min())

students = ds["Name"]
#Total Students:
print("Total Number of students are: ")
print(students.count())

Average of Marks is:
71.0
Maximum value in Marks is:
95
Minimum value in Marks is:
45
Total Number of students are:
5

**Task 02: Display Stdents with marks greater than or equal to 50 and less than or equal to 50**

In [ ]:
passed_students = ds[ds["Marks"]>=50]
print("Passed Students are: ")
print(passed_students)

failed_students = ds[ds["Marks"]<=50]
print("Failed Students are: ")
print(failed_students)

Passed Students are:
     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
Failed Students are:
   Name  Marks
4  Zain     45

**Task 03: Add a column named as "City"**

In [ ]:
from numpy import dsplit
ds["City"] = ["Karachi", "Lahore", "Islamabad", "Hyderabad", "Nawabshah"]
# display data with only karachi city
ds[ds["City"] == "Karachi"]

  Name  Marks     City
0  Ali     70  Karachi

**Task 04: Create a dataframe with columns: Name, courses, marks**

In [ ]:
std_info = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Courses": ["AI", "Web", "AI", "Web", "AI"],
    "Marks": [70, 85, 60, 95, 45]
}

ds = pd.DataFrame(std_info)
ds

     Name Courses  Marks
0     Ali      AI     70
1    Sara     Web     85
2   Ahmed      AI     60
3  Ayesha     Web     95
4    Zain      AI     45

In [ ]:
# Average Marks of each course

Avg_marks = ds.groupby("Courses")["Marks"].mean()
print("Average Marks of each course are: ")

print(Avg_marks)

Average Marks of each course are:
Courses
AI     58.333333
Web    90.000000
Name: Marks, dtype: float64

**task 05: Create a dataframe with some missing marks, then find missing values and fill them with avg of marks.**

In [ ]:
Data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Courses": ["AI", "Web", "AI", "Web", "AI"],
    "Roll_No" : [41456, 42678, 43256, 47653, 45980],
    "Marks": [70, None, 60, None, 45]

}

In [ ]:
ds = pd.DataFrame(Data)

In [ ]:
ds

     Name Courses  Roll_No  Marks
0     Ali      AI    41456   70.0
1    Sara     Web    42678    NaN
2   Ahmed      AI    43256   60.0
3  Ayesha     Web    47653    NaN
4    Zain      AI    45980   45.0

In [ ]:
# Find Missing Values:

Missing_values= ds.isnull()
print(Missing_values)

    Name  Courses  Roll_No  Marks
0  False    False    False  False
1  False    False    False   True
2  False    False    False  False
3  False    False    False   True
4  False    False    False  False

In [ ]:
print(ds.isnull().sum())

Name       0
Courses    0
Roll_No    0
Marks      2
dtype: int64

In [ ]:
ds['Marks'] = ds['Marks'].fillna(ds['Marks'].mean())
ds

     Name Courses  Roll_No      Marks
0     Ali      AI    41456  70.000000
1    Sara     Web    42678  58.333333
2   Ahmed      AI    43256  60.000000
3  Ayesha     Web    47653  58.333333
4    Zain      AI    45980  45.000000

In [ ]:
ds1 = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks": [70, 85, 60, 95, 45]

}

ds2 = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Courses": ["AI", "Web", "AI", "Web", "AI"],
    "Roll_no": [456, 789, 908, 678, 567]
}

ds1 = pd.DataFrame(ds1)
ds2 = pd.DataFrame(ds2)

final_ds = pd.merge(ds1 , ds2, on = "Name")
print(final_ds)

     Name  Marks Courses  Roll_no
0     Ali     70      AI      456
1    Sara     85     Web      789
2   Ahmed     60      AI      908
3  Ayesha     95     Web      678
4    Zain     45      AI      567